spring:
  liquibase:
    change-log: classpath:db/changelog/dbChangelog.xml
    drop-first: true
  datasource:
    url: jdbc:postgresql://ec2-52-71-69-66.compute-1.amazonaws.com:5432/dfus3sunb0nbme
    username: ehhzadyssxutjk
    password: 0daecc43be9961bb9aa42fd7cd7f9c47736b567dc4f2ce8213d25c38e657eb62
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

app:
  jwtSecret: JWTSecretKey
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher