spring:
  liquibase:
    change-log: classpath:db/changelog/dbChangelog.xml
    drop-first: false
  datasource:
    url: jdbc:postgresql://ec2-44-199-143-43.compute-1.amazonaws.com:5432/dfca4g4sge3l4f
    username: aydaksvmsigcmz
    password: 614e774c574406c63381f1874bcd990da5ccc92d825783ffcefb6147851b8468
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

app:
  jwtSecret: JWTSecretKey
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher